#include "widget.h"
#include "./ui_widget.h" //The ui_ files are generated by compiler via QMake
//Класс QGraphicsPixmapItem предоставляет элемент растрового изображения, который вы можете добавить на QGraphicsScene
#include <QGraphicsPixmapItem>
#include <QTextStream>
//дві глобальні змінні які вказують на необхідну кількість очок, щоб перейти на наступний рівень

Widget::Widget(QWidget *parent)
    : QWidget(parent)
    , ui(new Ui::Widget)
{
    setWindowFlags( Qt::Window | Qt::WindowTitleHint | Qt::CustomizeWindowHint ); //убрати верхні стандартні іконки

    ui->setupUi(this);

    scene = new Scene(this);
    scene->setSceneRect(-250,-300,500,600); // розмір сцени (гри)

    save = new savesFile();

    getItemImagesOnLvl();

    pixItem = new QGraphicsPixmapItem(QPixmap(backgroundPhrasePath)); //фон
    scene->addItem(pixItem); //встановити фон
    pixItem->setPos(QPointF(-262.5,-312.5)); //вирівняти фон

    lvlItem = new QGraphicsPixmapItem(QPixmap(lvlPhrasePath)); //current рівень зліва зверху
    scene->addItem(lvlItem);
    lvlItem->setPos(QPointF(-250,-300));
    scene->currentLvl(save->readFileLvl());

    ui->graphicsView->setScene(scene); //Устанавливает текущую сцену равной scene.

    scene->addFish();
    scene->setTopCounter();
    scene->showGameOverGraphics();
}

void Widget::showWidget()
{
    scene->startGame();
}

Widget::~Widget()
{
    delete ui;
}

void Widget::on_backMenu_clicked() //back to menu btn
{
    this->close();
    emit firstWindow(); // Вызываем сигнал на открытие главного окна
}

void Widget::continueGame()
{
    save->writeFileLvl("Lvl: 2");
    scene->setNullTopCounter();
    scene->hideReachedLvlGraphics();
    getItemImagesOnLvl();
    pixItem->setPixmap(QPixmap(backgroundPhrasePath));
    lvlItem->setPixmap(QPixmap(lvlPhrasePath));
    scene->currentLvl(save->readFileLvl());
    scene->startGame();
}

void Widget::getItemImagesOnLvl()
{
    switch(save->readFileLvl()) {
    case 1:
        lvlPhrasePath = ":/images/lvl_1.png";
        backgroundPhrasePath = ":/images/BG_2.png";
        break;
    case 2:
        lvlPhrasePath = ":/images/lvl_2.png";
        backgroundPhrasePath = ":/images/BG_3.png";
        break;
    case 0:
        lvlPhrasePath = ":/images/lvl_2.png";
        backgroundPhrasePath = ":/images/BG_3.png";
        break;
    }
}

void Widget::on_startAgain_clicked() //start again btn
{

    if((lvlTwoScore == save->getFileScore()) && (save->readFileLvl() == 1)) {
        save->writeFileLvl("Lvl: 1");
        save->writeFileScore(0);
        scene->bestScoreAndLvlInit();
        scene->hideReachedLvlGraphics();
    }

    if(lastLvlScore == save->getFileScore()) {
        return;
        save->writeFileLvl("Lvl: 2");
        save->writeFileScore(lvlTwoScore);
        //scene->bestScoreAndLvlInit();??????
        scene->hideReachedLvlGraphics();
    }


    scene->setNullTopCounter();
    getItemImagesOnLvl();
    pixItem->setPixmap(QPixmap(backgroundPhrasePath));
    lvlItem->setPixmap(QPixmap(lvlPhrasePath));
    scene->currentLvl(save->readFileLvl());
    scene->startGame();
}

//об'эднати два аналогычны коди
void Widget::mousePressEvent(QMouseEvent *event)
{
    if(event->button() == Qt::LeftButton && lvlTwoScore == save->getFileScore() && save->readFileLvl() == 1) {
        continueGame();
    }
    if(event->button() == Qt::LeftButton && lastLvlScore == save->getFileScore() && save->readFileLvl() == 2) {
        save->writeFileLvl("Lvl: end");
        scene->currentLvl(save->readFileLvl());
        scene->startGame();
    }
}


void Widget::on_restartGame_clicked() //restart game btn
{
    int score = save->getFileScore();
    if(score == lastLvlScore || (score == lvlTwoScore && save->readFileLvl() == 1)) scene->hideReachedLvlGraphics();

    save->writeFileLvl("Lvl: 1");
    save->writeFileScore(0);
    scene->setNullTopCounter();
    getItemImagesOnLvl(); //картинки для фона и уровня
    pixItem->setPixmap(QPixmap(backgroundPhrasePath));
    lvlItem->setPixmap(QPixmap(lvlPhrasePath));
    scene->currentLvl(1);
    scene->bestScoreAndLvlInit(); //в сцені ініціалізувати по нулі відповідні змінні
    scene->startGame();
}

void Widget::keyPressEvent(QKeyEvent *event)
{
    if(event->key() == Qt::Key_Space && lvlTwoScore == save->getFileScore() && save->readFileLvl() == 1) {
        continueGame();
    }
    if(event->key() == Qt::Key_Space && lastLvlScore == save->getFileScore() && save->readFileLvl() == 2) {
        save->writeFileLvl("Lvl: end");
        scene->currentLvl(save->readFileLvl());
        scene->startGame();
    }
}

